name: Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - id: temp-branch
        name: Create Temporary Branch
        uses: ./
        with:
          base: main

      - name: Log
        run: echo "Temporary branch is ${{ steps.temp-branch.outputs.branch }}"
